package com.wccgroup.coloja;

public class SpecialMembers
{
	// Lombok generated method for @Data classes, not present on @Value classes.
	public static final String CAN_EQUAL = "canEqual";
	// Lombok generated default method name when using @Builder.
	public static final String BUILDER = "builder";

	// Generated by jacoco
	public static final String JACOCO_HELPER_FIELD = "$jacocoData";
	public static final String JACOCO_HELPER_METHOD = "$jacocoInit";

	// Basic java methods and fields.
	public static final String CLASS = "class";
	public static final String EQUALS_METHOD = "equals";
	public static final String HASH_CODE = "hashCode";
	public static final String TO_STRING = "toString";
}
